image: ros:humble-ros-base-jammy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

ros2-humble:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y python3-colcon-common-extensions python3-rosdep
    - rosdep update
    - rosdep install --from-paths . --ignore-src -r -y --rosdistro humble
  script:
    - . /opt/ros/humble/setup.sh
    - colcon build --base-paths . --cmake-args -DBUILD_TESTING=ON
    - colcon test --event-handlers console_direct+
    - colcon test-result --verbose
