name: ROS 2 Humble

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y --rosdistro humble
      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --base-paths . --cmake-args -DBUILD_TESTING=ON
      - name: Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
